#pragma once
enum class GameState
{
	INTRO,
	ENTRANCE,
	ENDING,
	PLAY_SIDEVIEW_JASON,
	PLAY_SIDEVIEW_SOPHIA,
	PLAY_OVERHEAD,
	WEAPON_SELECT,
	SECTION_SWITCH_RIGHT,
	SECTION_SWITCH_LEFT,

	SECTION_SWITCH_OVERHEAD_LEFT,
	SECTION_SWITCH_OVERHEAD_RIGHT,
	SECTION_SWITCH_OVERHEAD_UP,
	SECTION_SWITCH_OVERHEAD_DOWN,

	SECTION_SWITCH_RIGHT_JASON,
	SECTION_SWITCH_LEFT_JASON,
	SCENE_SWITCH,
	RESET_LIFE,
	GAMEOVER,
};

