#pragma once

const int ZINDEX_DEFAULT = 0;
const int ZINDEX_BREAKABLE_BLOCKS = -1000;
const int ZINDEX_SOPHIA_BULLET = 50;
const int ZINDEX_SOPHIA = 100;
const int ZINDEX_JASONSIDEVIEW = 200;
const int ZINDEX_EXPLOSION = 1000;
const int ZINDEX_OVERHEAD_ENEMY_BULLET = -50;
